print("Hello World")
print("Turdali")

print("||=========||")
print("||         ||")
print("||         ||")
print("||         ||")
print("|| I Love  ||")
print("|| Vector! ||")
print("||         ||")
print("||         ||")
print("||         ||")
print("||=========||")

print("Og'abek")